### ISSUE TITLE
"Further application" contains dead links

### ISSUE THREAD

**Issue by cniesen** [Pi4J/pi4j.github.io#66]
The "Further application" links to Theremin and Photobooth are dead and return a 404.  It would be nice if @DieterHolz could restore the projects if they are still relevant.  Otherwise I'd suggest removing the links (see [occurrences](https://github.com/search?q=repo%3APi4J%2Fpi4j.github.io%20DieterHolz&type=code)).  Thanks.

Example:
https://www.pi4j.com/examples/components/simplebutton/

![image](https://github.com/user-attachments/assets/69ff7765-3c43-4c92-bb39-34d527630971)

**Comment by DieterHolz** [comment]
These links can be removed. Both projects are completely out of date.

**Comment by cniesen** [comment]
Thank's @DieterHolz .  

Pull request https://github.com/Pi4J/pi4j.github.io/pull/68 created.

**Comment by eitch** [comment]
PR merged
